### ISSUE TITLE
Shopify API url not working

### ISSUE THREAD

**Issue by DanishAbsar** [Shopify/shopify_python_api#314]
Hi,

Currently, I'm just playing around, with this library. I created a development store and a private app.
When I'm trying to create a product I got the following error:

Python 3.7.2
ShopifyAPI==5.0.1

Traceback (most recent call last):
  File "C:\Users\danish\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 877, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: '16xxxxxxx9exxxx5xxxxxxxxxxxxc5@my-chandola.myshopify.com'

Any help will be appreciated.

Thanks

**Comment by bboyadao** [comment]
```
i have same error here
shop_url = f"https://{API_KEY}:{PASSWORD}@{shop}/admin"
shopify.ShopifyResource.set_site(shop_url)
shop = shopify.Shop.current()


```
`AttributeError: type object 'ShopifyResource' has no attribute '_url'
`

**Comment by tonybeato** [comment]
Getting the same error

Python 3.7.2
ShopifyAPI==5.0.1

`shop_url = "https://%s:%s@%s.myshopify.com/admin" % (API_KEY, PASSWORD, MY_STORE)
shopify.ShopifyResource.set_site(shop_url)
shop = shopify.Shop.current()`

`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 877, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: '{password}@{my-store}.myshopify.com'`

**Comment by parchanco** [comment]
Same error here: 

Python 3.6
ShopifyAPI==5.0.0

`shop_url = "https://%s:%s@%s.myshopify.com/admin" % (self.shopify_api_key, self.shopify_password, self.shopify_name)`

`shopify.ShopifyResource.set_site(shop_url) #returns None `

`shopify.Shop.current() #returns {AttributeError}type object 'ShopifyResource' has no attribute '_url'`

**Comment by Xardasus** [comment]
Got the same error here too 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/myscript.py", line 6, in <module>
    product = shopify.Product.find(123123123123)
  File "C:\venv\lib\site-packages\pyactiveresource\activeresource.py", line 383, in find
    return cls._find_single(id_, **kwargs)
  File "C:\venv\lib\site-packages\pyactiveresource\activeresource.py", line 486, in _find_single
    return cls._build_object(cls.connection.get(path, cls.headers),
  File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 329, in get
    return self.format.decode(self._open('GET', path, headers=headers).body)
  File "C:\venv\lib\site-packages\shopify\base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1285, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1358, in __init__
    blocksize=blocksize)
  File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 841, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 882, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])

**Comment by Xardasus** [comment]
> Got the same error here too
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:/myscript.py", line 6, in 
> product = shopify.Product.find(123123123123)
> File "C:\venv\lib\site-packages\pyactiveresource\activeresource.py", line 383, in find
> return cls._find_single(id_, **kwargs)
> File "C:\venv\lib\site-packages\pyactiveresource\activeresource.py", line 486, in _find_single
> return cls._build_object(cls.connection.get(path, cls.headers),
> File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 329, in get
> return self.format.decode(self._open('GET', path, headers=headers).body)
> File "C:\venv\lib\site-packages\shopify\base.py", line 23, in _open
> self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
> File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 286, in _open
> http_response = self._handle_error(self._urlopen(request))
> File "C:\venv\lib\site-packages\pyactiveresource\connection.py", line 316, in _urlopen
> return urllib.request.urlopen(request, timeout=self.timeout)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
> response = self._open(req, data)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
> '_open', req)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
> result = func(*args)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open
> context=self._context, check_hostname=self._check_hostname)
> File "C:\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1285, in do_open
> h = http_class(host, timeout=req.timeout, **http_conn_args)
> File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1358, in **init**
> blocksize=blocksize)
> File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 841, in **init**
> (self.host, self.port) = self._get_hostport(host, port)
> File "C:\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 882, in _get_hostport
> raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])

I did override it by using the code:
shop_url = "https://xxxxx.myshopify.com/admin"
shopify.ShopifyResource.set_user("xxxxxxxxxxxxxxxxxxx")
shopify.ShopifyResource.set_password("xxxxxxxxxxxxxxxxxxxxxxxx")
shopify.ShopifyResource.set_site(shop_url)

**Comment by tylerball** [comment]
This should be fixed with version 5.0.1, please try it out: https://pypi.org/project/ShopifyAPI/5.0.1/

**Comment by parchanco** [comment]
> This should be fixed with version 5.0.1, please try it out: https://pypi.org/project/ShopifyAPI/5.0.1/

Tested with the same code and obtained the following error: InvalidURL("nonnumeric port: 'api_key@shopname.myshopify.com'",) 

Python 3.6
ShopifyAPI==5.0.1

**Comment by Xardasus** [comment]
> > This should be fixed with version 5.0.1, please try it out: https://pypi.org/project/ShopifyAPI/5.0.1/
> 
> Tested with the same code and obtained the following error: InvalidURL("nonnumeric port: '[api_key@shopname.myshopify.com](mailto:api_key@shopname.myshopify.com)'",)
> 
> Python 3.6
> ShopifyAPI==5.0.1

Hi parchanco,
you can try to use the workaround

instead of:
#shop_url = "https://'API_KEY':'PASSWORD'@SHOP_NAME.myshopify.com/admin"
#shopify.ShopifyResource.set_site(shop_url)

use:
shop_url = "https://SHOP_NAME.myshopify.com/admin"
shopify.ShopifyResource.set_user("API_KEY")
shopify.ShopifyResource.set_password("PASSWORD")
shopify.ShopifyResource.set_site(shop_url)

**Comment by parchanco** [comment]
> > > This should be fixed with version 5.0.1, please try it out: https://pypi.org/project/ShopifyAPI/5.0.1/
> > 
> > 
> > Tested with the same code and obtained the following error: InvalidURL("nonnumeric port: '[api_key@shopname.myshopify.com](mailto:api_key@shopname.myshopify.com)'",)
> > Python 3.6
> > ShopifyAPI==5.0.1
> 
> Hi parchanco,
> you can try to use a workaround
> 
> instead of:
> #shop_url = "https://'API_KEY':'PASSWORD'@SHOP_NAME.myshopify.com/admin"
> #shopify.ShopifyResource.set_site(shop_url)
> 
> use:
> shop_url = "https://SHOP_NAME.myshopify.com/admin"
> shopify.ShopifyResource.set_user("API_KEY")
> shopify.ShopifyResource.set_password("PASSWORD")
> shopify.ShopifyResource.set_site(shop_url)

Tested and still not working, i tried the connection credentials with postman and works fine.  
The set_site function has always been returning None. The Shop.current() is still returning the previous error.

**Comment by hgolov** [comment]
I encountered this issue (InvalidURL("nonnumeric port: 'api_key@shopname.myshopify.com'",))  today, and the workaround worked for me.

shop_url = "https://xxxxx.myshopify.com/admin"
shopify.ShopifyResource.set_user("API_KEY")
shopify.ShopifyResource.set_password("PASSWORD")
shopify.ShopifyResource.set_site(shop_url)

Thanks!

**Comment by parchanco** [comment]
> I encountered this issue (InvalidURL("nonnumeric port: '[api_key@shopname.myshopify.com](mailto:api_key@shopname.myshopify.com)'",)) today, and the workaround worked for me.
> 
> shop_url = "https://xxxxx.myshopify.com/admin"
> shopify.ShopifyResource.set_user("API_KEY")
> shopify.ShopifyResource.set_password("PASSWORD")
> shopify.ShopifyResource.set_site(shop_url)
> 
> Thanks!

I tried the following code:
```
shop_url = "https://%s.myshopify.com/admin" % (self.shopify_name)
                shopify.ShopifyResource.set_user(self.shopify_api_key)
                shopify.ShopifyResource.set_password(self.shopify_password)
                shopify.ShopifyResource.set_site(shop_url)

                # Get the current shoop
                shop = shopify.Shop.current()
```
and get the following error
`Error(URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),),)`

**Comment by monokal** [comment]
Same issue. The test pipeline around breaking changes is leaving something to be desired.

**Comment by cmagnoc5561** [comment]
> > > > This should be fixed with version 5.0.1, please try it out: https://pypi.org/project/ShopifyAPI/5.0.1/
> > > 
> > > 
> > > Tested with the same code and obtained the following error: InvalidURL("nonnumeric port: '[api_key@shopname.myshopify.com](mailto:api_key@shopname.myshopify.com)'",)
> > > Python 3.6
> > > ShopifyAPI==5.0.1
> > 
> > 
> > Hi parchanco,
> > you can try to use a workaround
> > instead of:
> > #shop_url = "https://'API_KEY':'PASSWORD'@SHOP_NAME.myshopify.com/admin"
> > #shopify.ShopifyResource.set_site(shop_url)
> > use:
> > shop_url = "https://SHOP_NAME.myshopify.com/admin"
> > shopify.ShopifyResource.set_user("API_KEY")
> > shopify.ShopifyResource.set_password("PASSWORD")
> > shopify.ShopifyResource.set_site(shop_url)
> 
> Tested and still not working, i tried the connection credentials with postman and works fine.
> The set_site function has always been returning None. The Shop.current() is still returning the previous error.

Hi guys! Just to reaffirm that the workaround has been working for me in different scripts now. I've tested the workaround with both versions of the Shopify API (4.00 and 5.01) and running with Windows 10 and Mac OS 10.14.4. I hope this can help!

**Comment by adam-rudd-myob** [comment]
Can we please update the "Getting Started" documentation to reflect this? I was stuck for a good hour before searching through the issues tab

**Comment by ascheucher** [comment]
We can upgrade the documentation. [Actually I did](https://github.com/Shopify/shopify_python_api/pull/319)
Now just somebody from Shopify has to merge it.

Everybody can do it. It's a shame nobody else did till now ;)

**Comment by tylerball** [comment]
Apologies for the delay in addressing this, I think I've managed to track down the root cause and have opened a PR #330.

**Comment by DanishAbsar** [comment]
Awesome

Thanks @tylerball

**Comment by raveenb** [comment]
this approach worked for me

shop_url = "https://xxxxx.myshopify.com/admin"
shopify.ShopifyResource.set_user("API_KEY")
shopify.ShopifyResource.set_password("PASSWORD")
shopify.ShopifyResource.set_site(shop_url)

**Comment by Nishanth14** [comment]
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'shop_name.myshopify.com'. 

I think documentation is not still updated

Below one works

shop_url = "https://xxxxx.myshopify.com/admin"
shopify.ShopifyResource.set_user("API_KEY")
shopify.ShopifyResource.set_password("PASSWORD")
shopify.ShopifyResource.set_site(shop_url)
